### ISSUE TITLE
P2P-Code-Review

### ISSUE THREAD

**Issue by ITurres** [NitBravoA92/leaderboard-api#3]
### Great job so far!💪

By @ITurres:

#### Hi @NitBravoA92! :D, your project looks very good, is easy to understand, great naming convention, and is very well structured.  great job!💪

✅ Good commit history.
✅ ES6 syntax.
✅ Way to go on using object destructuring!🎯
✅ Clear and readable variable/function naming convention.

Keep up the good work 🏆

---

By @grauJavier:

Please consider using the suggested code improvement: 
```js
const gameId = localStorage.getItem('gameId') || (await newGameId());
```
 and kindly relocate the:

```js
 localStorage.setItem('game-id', gameId)
```
 operation inside the newGameId() function.

---

**Comment by NitBravoA92** [comment]
# Changes Applied ✅

### Hi, Team! @ITurres @grauJavier 

I really thank you so much 🙇‍♂️, for taking the time to attend my presentation and read my code carefully.

I really appreciate your feedback ⭐and the suggestions you gave me 📃 to improve my code.

In the following pull request, you have a summary of the changes ♻️ I have made to my code based on your valuable suggestions:

[PR: Suggested Changes in Peer to Peer Code Review](https://github.com/NitBravoA92/leaderboard-api/pull/5)

If you can review this pull request and give me your impressions about the changes applied, I would greatly appreciate it.

I think the changes you have suggested to me have been very objective 🥇 and have made my code look more understandable and better organized. So, thanks again for helping me improve the structure of my code.

I kindly ask 🙏 dear team 🤵 that if there is not any other kind of issue 🦯 in this project, please close this issue. 📃 But if you feel that the changes were not applied correctly, please let me know in a comment below or contact me via Slack, I am available on Microverse UTC-6 time zone.

**Comment by ITurres** [comment]
## Hi @NitBravoA92

### Well done applying the suggested changes!💪

### Keep up the good work 🏆

---

## ISSUE #3

### Status: Ready to be closed 🏁

---

**Comment by ITurres** [comment]
## Hi @NitBravoA92

### Well done applying the suggested changes!💪

### Keep up the good work 🏆

---

## ISSUE #3

### Status: Ready to be closed 🏁

---
